# version: 2.0

# jobs:
#     build:
#         docker:
#             - image: circleci/python:3.6
#             - image: circleci/node
#             - image: circleci/postgres:latest-postgis
#               environment: &postgres_variables
#                 DB_NAME: $DB_NAME
#                 DB_USER: $DB_USER
#                 DB_PASSWORD: $DB_PASSWORD
#         steps:
#             - checkout
#             # create db with user
#             run:

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          key:
      - run:
          command: |
            python3 -m venv env
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "Install node modules"
          command: npm install

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
