version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2 # Invoke the Heroku orb
jobs:
  build_django:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      #   - run:
      #       name: "Install node modules"
      #       command: npm install

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Running tests
          command: |
            . env/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
  build_node:
    working_directory: ~/edutrip
    docker:
      - image: cimg/node:14.13.0

    steps:
      - run:
          name: "install node modules"
          command: npm run install

workflows:
  heroku_deploy:
    jobs:
      - build_django
      - build_node
      - heroku/deploy-via-git:
          requires:
            - build_django
            - build_node
          filters:
            branches:
              only: main
