# Generated by Django 2.0.7 on 2018-07-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('number_of_visitors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('Kiambere', 'Kiambere'), ('Masinga', 'Masinga'), ('Kindaruma', 'Kindaruma'), ('Gitaru', 'Gitaru'), ('Kamburu', 'Kamburu')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_of_visit', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Institution')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.PowerStations')),
            ],
        ),
    ]
