# Generated by Django 2.0.7 on 2018-07-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='station',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='PowerStations',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
