# Generated by Django 2.0.7 on 2018-08-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_powerstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('10:00 a.m.', '10:00 a.m.'), ('2:00 p.m.', '2:00 p.m.')], max_length=10)),
                ('date', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Institution')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.PowerStation')),
            ],
        ),
    ]
