# Generated by Django 2.0.7 on 2018-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookingApp', '0002_auto_20180712_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('po_box', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('number_of_visitors', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
