# Generated by Django 2.0.7 on 2018-07-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_createInstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('available', models.BooleanField()),
                ('unavailable_from', models.DateField(blank=True)),
                ('unavailable_until', models.DateField(blank=True)),
            ],
        ),
    ]
