# Generated by Django 2.0.7 on 2018-08-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(),
        ),
    ]
