# Generated by Django 2.0.7 on 2018-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0005_createDate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerstation',
            name='name',
            field=models.CharField(choices=[('Masinga', 'Masinga'), ('Kamburu', 'Kamburu'), ('Gitaru', 'Gitaru'), ('Kindaruma', 'Kindaruma'), ('Kiambere', 'Kiambere')], max_length=20),
        ),
        migrations.AlterField(
            model_name='powerstation',
            name='unavailable_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerstation',
            name='unavailable_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
