# Generated by Django 2.0.7 on 2018-07-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0006_auto_20180712_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=15)),
                ('time', models.CharField(choices=[('10:00 a.m.', '10:00 a.m.'), ('2:00 p.m.', '2:00 p.m.')], max_length=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.TripDate')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Institution')),
            ],
        ),
    ]
