# Generated by Django 2.0.7 on 2018-07-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0007_createTrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.PowerStation'),
        ),
    ]
