# Generated by Django 2.0.7 on 2018-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0008_changedStationField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(),
        ),
    ]
