# Generated by Django 2.0.7 on 2018-07-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0009_auto_20180712_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripDate',
        ),
        migrations.AddField(
            model_name='trip',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
